"""Add approver first and last name to AccessRequest

Revision ID: 123a7729522b
Revises: 
Create Date: 2024-05-28 16:16:02.245112

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '123a7729522b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('access_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('approver_first_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('approver_last_name', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('access_request', schema=None) as batch_op:
        batch_op.drop_column('approver_last_name')
        batch_op.drop_column('approver_first_name')

    # ### end Alembic commands ###
