"""Add is_internal_access to AccessRequest

Revision ID: 1fcf0f94e7d9
Revises: 123a7729522b
Create Date: 2024-05-28 16:31:33.624845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fcf0f94e7d9'
down_revision = '123a7729522b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('access_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_internal_access', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('access_request', schema=None) as batch_op:
        batch_op.drop_column('is_internal_access')

    # ### end Alembic commands ###
