version: '3.7'

services:
  user-service:
    build: ./user-service
    ports:
      - "5001:5000"
    environment:
      - DATABASE_URL=postgresql://user:password@db/user_service

  access-service:
    build: ./access-service
    ports:
      - "5002:5000"
    environment:
      - DATABASE_URL=postgresql://user:password@db/access_service

  customer-service:
    build: ./customer-service
    ports:
      - "5003:5000"
    environment:
      - DATABASE_URL=postgresql://user:password@db/customer_service

  db:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password

  api-gateway:
    build: ./api-gateway
    ports:
      - "5000:5000"